from __future__ import annotations

from dataclasses import dataclass, field
from enum import Enum
from typing import Any


@dataclass
class WordTimestamp:
    """A single word with its start and end timestamps."""
    word: str
    start: float  # seconds
    end: float    # seconds


@dataclass
class Segment:
    """A single transcript segment with timing and text."""
    start: float   # seconds
    end: float     # seconds
    text: str
    words: list[WordTimestamp] = field(default_factory=list)


@dataclass
class Transcript:
    """A collection of transcript segments with serialization support."""
    segments: list[Segment]

    def to_dict(self) -> dict[str, Any]:
        """Serialize the Transcript to a JSON-compatible dictionary."""
        return {
            "segments": [
                {
                    "start": seg.start,
                    "end": seg.end,
                    "text": seg.text,
                    "words": [
                        {"word": w.word, "start": w.start, "end": w.end}
                        for w in seg.words
                    ],
                }
                for seg in self.segments
            ]
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> "Transcript":
        """Deserialize a Transcript from a dictionary."""
        segments = []
        for s in data.get("segments", []):
            words = [
                WordTimestamp(word=w["word"], start=w["start"], end=w["end"])
                for w in s.get("words", [])
            ]
            segments.append(
                Segment(start=s["start"], end=s["end"], text=s["text"], words=words)
            )
        return cls(segments=segments)


@dataclass
class ScoredSegment:
    """A transcript segment with computed scores."""
    segment: Segment
    text_score: float    # [0.0, 1.0]
    audio_score: float   # [0.0, 1.0]
    llm_score: float     # [0.0, 1.0], 0.0 if LLM disabled
    clip_score: float    # weighted combination
    llm_metadata: "LLMMetadata | None" = None  # YouTube metadata, set when LLM enabled
    is_audio_spike: bool = False  # True if selected purely for audio spikes (bypassed LLM)


@dataclass
class LLMMetadata:
    """YouTube Shorts metadata generated by the LLM for a candidate clip."""
    title: str
    description: str
    tags: list[str]


@dataclass
class Clip:
    """A selected video clip with timing, score, and source segment references."""
    start: float              # seconds, >= 0.0
    end: float                # seconds, <= video_duration
    score: float              # clip_score of the seed segment
    rank: int                 # 1-based rank by score
    segment_indices: list[int]  # indices into transcript.segments
    is_audio_spike: bool = False  # True if this clip was selected purely for audio spikes (bypassed LLM)


@dataclass
class SRTEntry:
    """A single entry in an SRT subtitle file."""
    index: int
    start: float   # seconds, relative to clip start
    end: float     # seconds, relative to clip start
    text: str


@dataclass
class FacecamRegion:
    """Describes the detected facecam pip region in the source frame."""
    x: int          # left edge in source frame pixels
    y: int          # top edge in source frame pixels
    width: int      # crop width
    height: int     # crop height
    corner: str     # "top-left" | "top-right" | "bottom-left" | "bottom-right"
    confidence: float  # 0.0–1.0, how confident the detection is


@dataclass
class CanvasLayout:
    """Describes the 9:16 vertical canvas layout with facecam and gameplay regions."""
    canvas_width: int       # 1080
    canvas_height: int      # 1920
    facecam_x: int          # 0
    facecam_y: int          # 0
    facecam_width: int      # 1080
    facecam_height: int     # ~672 (35% of 1920)
    gameplay_x: int         # 0
    gameplay_y: int         # ~672
    gameplay_width: int     # 1080
    gameplay_height: int    # ~1248 (65% of 1920)


@dataclass
class FilterFragment:
    """An FFmpeg filter-graph fragment produced by a sub-component."""
    filter_str: str         # FFmpeg -vf / -filter_complex fragment
    input_label: str        # e.g. "[v0]"
    output_label: str       # e.g. "[canvas]"
    extra_inputs: list[str] = field(default_factory=list)  # additional -i paths needed


class SubtitleStyle(Enum):
    """Visual style for animated subtitles in the shorts formatter."""
    BUBBLE    = "bubble"    # rounded outline, bold, slight scale pop on entry
    POPUP     = "popup"     # words appear one at a time with a scale-in animation
    HIGHLIGHT = "highlight" # active word gets a colored background box
    KARAOKE   = "karaoke"   # word color changes as it is spoken


@dataclass
class AudioFeatures:
    """Enhanced audio features for viral clip detection.
    
    All scores are normalized to [0.0, 1.0] using percentile clipping (5th-95th)
    to prevent outliers from skewing the distribution.
    
    Temporal resolution: 0.5 second windows
    """
    time: float              # timestamp in seconds
    volume_score: float      # RMS energy (normalized 0-1)
    pitch_score: float       # F0 fundamental frequency (normalized 0-1)
    excitement_score: float  # 0.6 × volume + 0.4 × pitch
    silence_score: float     # 1.0 - volume (detects pauses)
